// Her dilde gerçek kelime + cümle örnekleri (5 etap)
// PACKS: tam müfredat | REAL: diğer diller için gerçek örnekler

const PACKS = {
  en: {
    s1: {
      words: [["Hello","Merhaba"],["Hi","Selam"],["Good morning","Günaydın"],["Good night","İyi geceler"],["Please","Lütfen"],["Thank you","Teşekkürler"],["Sorry","Özür dilerim"],["Yes","Evet"],["No","Hayır"],["Okay","Tamam"],["Friend","Arkadaş"],["Name","İsim"]],
      phrases: [["How are you?","Nasılsın?"],["I'm fine, thanks.","İyiyim, teşekkürler."],["What's your name?","Adın ne?"],["Nice to meet you.","Tanıştığımıza memnun oldum."],["See you later.","Sonra görüşürüz."],["Have a nice day.","İyi günler."]],
      lesson: "Hello nötr, Hi samimi. How are you? → I'm fine / Good / Not bad."
    },
    s2: {
      words: [["Water","Su"],["Food","Yemek"],["Bread","Ekmek"],["Coffee","Kahve"],["Tea","Çay"],["Money","Para"],["Price","Fiyat"],["Street","Sokak"],["Station","İstasyon"],["Bathroom","Tuvalet"],["One","Bir"],["Ten","On"]],
      phrases: [["Where is the bathroom?","Tuvalet nerede?"],["How much is this?","Bu ne kadar?"],["I need water.","Suya ihtiyacım var."],["The station, please.","İstasyon, lütfen."],["I don't understand.","Anlamıyorum."],["Can you help me?","Bana yardım eder misin?"]],
      lesson: "How much is this? alışverişte, Where is ...? yol sormada."
    },
    s3: {
      words: [["Today","Bugün"],["Tomorrow","Yarın"],["Yesterday","Dün"],["Now","Şimdi"],["Later","Sonra"],["Morning","Sabah"],["Evening","Akşam"],["Week","Hafta"],["Time","Zaman"],["Hour","Saat"],["Busy","Meşgul"],["Free","Boş"]],
      phrases: [["What time is it?","Saat kaç?"],["I'm busy today.","Bugün meşgulüm."],["Let's meet tomorrow.","Yarın buluşalım."],["Are you free?","Boş musun?"],["See you on Monday.","Pazartesi görüşürüz."],["What are you doing?","Ne yapıyorsun?"]],
      lesson: "Plan: Let's meet tomorrow. Saat: What time is it?"
    },
    s4: {
      words: [["Happy","Mutlu"],["Sad","Üzgün"],["Tired","Yorgun"],["Work","İş"],["School","Okul"],["Travel","Seyahat"],["Hotel","Otel"],["Ticket","Bilet"],["Important","Önemli"],["Problem","Sorun"],["Easy","Kolay"],["Difficult","Zor"]],
      phrases: [["I feel tired.","Yorgun hissediyorum."],["I work from home.","Evden çalışıyorum."],["I need a ticket.","Bilete ihtiyacım var."],["It's important.","Bu önemli."],["No problem.","Sorun değil."],["It was difficult.","Zordu."]],
      lesson: "I feel ... duygu; No problem günlük cevap."
    },
    s5: {
      words: [["Because","Çünkü"],["However","Ancak"],["Always","Her zaman"],["Never","Asla"],["Often","Sık sık"],["Sometimes","Bazen"],["Already","Çoktan"],["Still","Hâlâ"],["Enough","Yeterli"],["Together","Birlikte"],["Without","Olmadan"],["During","Sırasında"]],
      phrases: [["I already know this.","Bunu zaten biliyorum."],["We can go together.","Birlikte gidebiliriz."],["I never do that.","Bunu asla yapmam."],["It's still early.","Hâlâ erken."],["That's enough.","Bu kadar yeter."],["During the day...","Gün içinde..."]],
      lesson: "Already / still ve sıklık zarfları sınavda çıkar."
    }
  },
  de: {
    s1: { words:[["Hallo","Merhaba"],["Guten Morgen","Günaydın"],["Danke","Teşekkürler"],["Bitte","Lütfen"],["Ja","Evet"],["Nein","Hayır"],["Entschuldigung","Özür dilerim"],["Freund","Arkadaş"],["Name","İsim"],["Gut","İyi"],["Schlecht","Kötü"],["Tschüss","Hoşça kal"]], phrases:[["Wie geht's?","Nasılsın?"],["Mir geht's gut.","İyiyim."],["Wie heißt du?","Adın ne?"],["Schön dich kennenzulernen.","Memnun oldum."],["Gute Nacht.","İyi geceler."],["Bis später.","Sonra görüşürüz."]], lesson:"Sie resmi, du samimi." },
    s2: { words:[["Wasser","Su"],["Brot","Ekmek"],["Kaffee","Kahve"],["Geld","Para"],["Straße","Sokak"],["Bahnhof","İstasyon"],["Toilette","Tuvalet"],["Eins","Bir"],["Zehn","On"],["Heute","Bugün"],["Morgen","Yarın"],["Hilfe","Yardım"]], phrases:[["Wo ist die Toilette?","Tuvalet nerede?"],["Wie viel kostet das?","Ne kadar?"],["Ich verstehe nicht.","Anlamıyorum."],["Einen Kaffee bitte.","Bir kahve lütfen."],["Können Sie helfen?","Yardım edebilir misiniz?"],["Ich brauche Wasser.","Suya ihtiyacım var."]], lesson:"Wo / Wie / Was soru kelimeleri." },
    s3: { words:[["Zeit","Zaman"],["Stunde","Saat"],["Woche","Hafta"],["Montag","Pazartesi"],["Frei","Boş"],["Beschäftigt","Meşgul"],["Jetzt","Şimdi"],["Später","Sonra"],["Arbeit","İş"],["Schule","Okul"],["Haus","Ev"],["Stadt","Şehir"]], phrases:[["Wie spät ist es?","Saat kaç?"],["Ich bin beschäftigt.","Meşgulüm."],["Bis morgen.","Yarına kadar."],["Hast du Zeit?","Zamanın var mı?"],["Wir treffen uns später.","Sonra buluşuruz."],["Ich gehe nach Hause.","Eve gidiyorum."]], lesson:"Wie spät ist es? = saat kaç?" },
    s4: { words:[["Glücklich","Mutlu"],["Müde","Yorgun"],["Wichtig","Önemli"],["Problem","Sorun"],["Reise","Seyahat"],["Hotel","Otel"],["Ticket","Bilet"],["Einfach","Kolay"],["Schwer","Zor"],["Familie","Aile"],["Liebe","Aşk"],["Wetter","Hava"]], phrases:[["Ich bin müde.","Yorgunum."],["Kein Problem.","Sorun değil."],["Gute Reise!","İyi yolculuklar!"],["Es ist wichtig.","Önemli."],["Wie ist das Wetter?","Hava nasıl?"],["Ich liebe das.","Bunu seviyorum."]], lesson:"Kein Problem sık cevap." },
    s5: { words:[["Immer","Her zaman"],["Nie","Asla"],["Oft","Sık"],["Manchmal","Bazen"],["Schon","Çoktan"],["Noch","Hâlâ"],["Zusammen","Birlikte"],["Ohne","Olmadan"],["Weil","Çünkü"],["Aber","Ama"],["Oder","Veya"],["Also","Yani"]], phrases:[["Ich weiß schon.","Zaten biliyorum."],["Noch nicht.","Henüz değil."],["Kommst du mit?","Birlikte gelir misin?"],["Ohne Zucker bitte.","Şekersiz lütfen."],["Ich lerne, weil...","Öğreniyorum çünkü..."],["Alles klar.","Her şey tamam."]], lesson:"schon / noch nicht sınav klasik." }
  },
  es: {
    s1: { words:[["Hola","Merhaba"],["Gracias","Teşekkürler"],["Por favor","Lütfen"],["Sí","Evet"],["No","Hayır"],["Perdón","Affedersin"],["Amigo","Arkadaş"],["Nombre","İsim"],["Buenos días","Günaydın"],["Buenas noches","İyi geceler"],["Bien","İyi"],["Adiós","Hoşça kal"]], phrases:[["¿Cómo estás?","Nasılsın?"],["Estoy bien.","İyiyim."],["¿Cómo te llamas?","Adın ne?"],["Mucho gusto.","Memnun oldum."],["Hasta luego.","Sonra görüşürüz."],["Que tengas un buen día.","İyi günler."]], lesson:"¿...? soru işaretleri." },
    s2: { words:[["Agua","Su"],["Comida","Yemek"],["Café","Kahve"],["Dinero","Para"],["Calle","Sokak"],["Estación","İstasyon"],["Baño","Tuvalet"],["Uno","Bir"],["Diez","On"],["Hoy","Bugün"],["Mañana","Yarın"],["Ayuda","Yardım"]], phrases:[["¿Dónde está el baño?","Tuvalet nerede?"],["¿Cuánto cuesta?","Ne kadar?"],["No entiendo.","Anlamıyorum."],["Un café, por favor.","Bir kahve lütfen."],["Necesito ayuda.","Yardıma ihtiyacım var."],["La cuenta, por favor.","Hesap lütfen."]], lesson:"La cuenta = hesap." },
    s3: { words:[["Tiempo","Zaman"],["Hora","Saat"],["Semana","Hafta"],["Lunes","Pazartesi"],["Libre","Boş"],["Ocupado","Meşgul"],["Ahora","Şimdi"],["Después","Sonra"],["Trabajo","İş"],["Escuela","Okul"],["Casa","Ev"],["Ciudad","Şehir"]], phrases:[["¿Qué hora es?","Saat kaç?"],["Estoy ocupado.","Meşgulüm."],["Hasta mañana.","Yarın görüşürüz."],["¿Estás libre?","Boş musun?"],["Nos vemos luego.","Sonra görüşürüz."],["Voy a casa.","Eve gidiyorum."]], lesson:"¿Qué hora es?" },
    s4: { words:[["Feliz","Mutlu"],["Cansado","Yorgun"],["Importante","Önemli"],["Problema","Sorun"],["Viaje","Seyahat"],["Hotel","Otel"],["Boleto","Bilet"],["Fácil","Kolay"],["Difícil","Zor"],["Familia","Aile"],["Amor","Aşk"],["Clima","Hava"]], phrases:[["Estoy cansado.","Yorgunum."],["No hay problema.","Sorun yok."],["¡Buen viaje!","İyi yolculuklar!"],["Es importante.","Önemli."],["¿Cómo está el clima?","Hava nasıl?"],["Me gusta esto.","Bunu beğeniyorum."]], lesson:"Me gusta = beğeniyorum." },
    s5: { words:[["Siempre","Her zaman"],["Nunca","Asla"],["A menudo","Sık sık"],["A veces","Bazen"],["Ya","Çoktan"],["Todavía","Hâlâ"],["Juntos","Birlikte"],["Sin","Olmadan"],["Porque","Çünkü"],["Pero","Ama"],["O","Veya"],["Entonces","O zaman"]], phrases:[["Ya lo sé.","Zaten biliyorum."],["Todavía no.","Henüz değil."],["Vamos juntos.","Birlikte gidelim."],["Sin azúcar.","Şekersiz."],["Porque estoy aprendiendo.","Çünkü öğreniyorum."],["Está bien.","Tamam."]], lesson:"Ya / todavía no." }
  },
  fr: {
    s1: { words:[["Bonjour","Merhaba"],["Merci","Teşekkürler"],["S'il vous plaît","Lütfen"],["Oui","Evet"],["Non","Hayır"],["Pardon","Affedersiniz"],["Ami","Arkadaş"],["Nom","İsim"],["Bonsoir","İyi akşamlar"],["Bonne nuit","İyi geceler"],["Bien","İyi"],["Au revoir","Hoşça kal"]], phrases:[["Comment ça va?","Nasılsın?"],["Ça va bien.","İyiyim."],["Comment tu t'appelles?","Adın ne?"],["Enchanté.","Memnun oldum."],["À plus tard.","Sonra görüşürüz."],["Bonne journée.","İyi günler."]], lesson:"tu samimi, vous resmi." },
    s2: { words:[["Eau","Su"],["Pain","Ekmek"],["Café","Kahve"],["Argent","Para"],["Rue","Sokak"],["Gare","İstasyon"],["Toilette","Tuvalet"],["Un","Bir"],["Dix","On"],["Aujourd'hui","Bugün"],["Demain","Yarın"],["Aide","Yardım"]], phrases:[["Où sont les toilettes?","Tuvalet nerede?"],["Combien ça coûte?","Ne kadar?"],["Je ne comprends pas.","Anlamıyorum."],["Un café, s'il vous plaît.","Bir kahve lütfen."],["Aidez-moi.","Bana yardım edin."],["L'addition, s'il vous plaît.","Hesap lütfen."]], lesson:"L'addition = hesap." },
    s3: { words:[["Temps","Zaman"],["Heure","Saat"],["Semaine","Hafta"],["Lundi","Pazartesi"],["Libre","Boş"],["Occupé","Meşgul"],["Maintenant","Şimdi"],["Plus tard","Sonra"],["Travail","İş"],["École","Okul"],["Maison","Ev"],["Ville","Şehir"]], phrases:[["Quelle heure est-il?","Saat kaç?"],["Je suis occupé.","Meşgulüm."],["À demain.","Yarın görüşürüz."],["Tu es libre?","Boş musun?"],["On se voit plus tard.","Sonra görüşürüz."],["Je rentre à la maison.","Eve dönüyorum."]], lesson:"Quelle heure est-il?" },
    s4: { words:[["Heureux","Mutlu"],["Fatigué","Yorgun"],["Important","Önemli"],["Problème","Sorun"],["Voyage","Seyahat"],["Hôtel","Otel"],["Billet","Bilet"],["Facile","Kolay"],["Difficile","Zor"],["Famille","Aile"],["Amour","Aşk"],["Météo","Hava"]], phrases:[["Je suis fatigué.","Yorgunum."],["Pas de problème.","Sorun değil."],["Bon voyage!","İyi yolculuklar!"],["C'est important.","Önemli."],["Quel temps fait-il?","Hava nasıl?"],["J'aime ça.","Bunu seviyorum."]], lesson:"J'aime = seviyorum." },
    s5: { words:[["Toujours","Her zaman"],["Jamais","Asla"],["Souvent","Sık"],["Parfois","Bazen"],["Déjà","Çoktan"],["Encore","Hâlâ"],["Ensemble","Birlikte"],["Sans","Olmadan"],["Parce que","Çünkü"],["Mais","Ama"],["Ou","Veya"],["Donc","Bu yüzden"]], phrases:[["Je sais déjà.","Zaten biliyorum."],["Pas encore.","Henüz değil."],["Allons-y ensemble.","Birlikte gidelim."],["Sans sucre.","Şekersiz."],["Parce que j'apprends.","Çünkü öğreniyorum."],["D'accord.","Tamam."]], lesson:"Déjà / pas encore." }
  },
  ja: {
    s1: { words:[["こんにちは","Merhaba"],["おはよう","Günaydın"],["ありがとう","Teşekkürler"],["すみません","Özür dilerim"],["はい","Evet"],["いいえ","Hayır"],["名前","İsim"],["友達","Arkadaş"],["水","Su"],["ください","Lütfen"],["元気","İyi"],["さようなら","Hoşça kal"]], phrases:[["お元気ですか？","Nasılsınız?"],["元気です。","İyiyim."],["名前は何ですか？","Adınız ne?"],["はじめまして。","Memnun oldum."],["また後で。","Sonra görüşürüz."],["よろしくお願いします。","Rica ederim."]], lesson:"Kibarlık ekleri önemli." },
    s2: { words:[["トイレ","Tuvalet"],["駅","İstasyon"],["いくら","Ne kadar"],["どこ","Nerede"],["今日","Bugün"],["明日","Yarın"],["今","Şimdi"],["食べ物","Yiyecek"],["お茶","Çay"],["お金","Para"],["助け","Yardım"],["少し","Biraz"]], phrases:[["トイレはどこですか？","Tuvalet nerede?"],["いくらですか？","Ne kadar?"],["わかりません。","Anlamıyorum."],["水をください。","Su lütfen."],["助けてください。","Yardım edin."],["英語が話せますか？","İngilizce konuşur musunuz?"]], lesson:"〜はどこですか？" },
    s3: { words:[["時間","Zaman"],["時","Saat"],["週","Hafta"],["月曜日","Pazartesi"],["暇","Boş"],["忙しい","Meşgul"],["後で","Sonra"],["家","Ev"],["学校","Okul"],["仕事","İş"],["都市","Şehir"],["会う","Buluşmak"]], phrases:[["今何時ですか？","Saat kaç?"],["忙しいです。","Meşgulüm."],["また明日。","Yarın görüşürüz."],["暇ですか？","Boş musun?"],["後で会いましょう。","Sonra buluşalım."],["家に帰ります。","Eve dönüyorum."]], lesson:"今何時ですか？" },
    s4: { words:[["嬉しい","Mutlu"],["疲れた","Yorgun"],["大切","Önemli"],["問題","Sorun"],["旅行","Seyahat"],["ホテル","Otel"],["切符","Bilet"],["簡単","Kolay"],["難しい","Zor"],["家族","Aile"],["愛","Aşk"],["天気","Hava"]], phrases:[["疲れました。","Yoruldum."],["問題ないです。","Sorun yok."],["良い旅行を！","İyi yolculuklar!"],["大切です。","Önemli."],["天気はどうですか？","Hava nasıl?"],["これが好きです。","Bunu seviyorum."]], lesson:"〜が好きです" },
    s5: { words:[["いつも","Her zaman"],["決して","Asla"],["よく","Sık"],["時々","Bazen"],["もう","Artık"],["まだ","Hâlâ"],["一緒に","Birlikte"],["なしで","Olmadan"],["から","Çünkü"],["でも","Ama"],["または","Veya"],["それで","Bu yüzden"]], phrases:[["もう知っています。","Zaten biliyorum."],["まだです。","Henüz değil."],["一緒に行きましょう。","Birlikte gidelim."],["砂糖なしで。","Şekersiz."],["勉強しているからです。","Çünkü çalışıyorum."],["大丈夫です。","Sorun değil."]], lesson:"もう / まだ" }
  },
  ar: {
    s1: { words:[["مرحبا","Merhaba"],["صباح الخير","Günaydın"],["شكرا","Teşekkürler"],["من فضلك","Lütfen"],["نعم","Evet"],["لا","Hayır"],["اسم","İsim"],["صديق","Arkadaş"],["ماء","Su"],["حسنا","Tamam"],["وداعا","Hoşça kal"],["عفوا","Rica ederim"]], phrases:[["كيف حالك؟","Nasılsın?"],["أنا بخير.","İyiyim."],["ما اسمك؟","Adın ne?"],["تشرفنا.","Memnun oldum."],["إلى اللقاء.","Görüşürüz."],["يوم سعيد.","İyi günler."]], lesson:"Sağdan sola yazılır." },
    s2: { words:[["طعام","Yemek"],["قهوة","Kahve"],["شارع","Sokak"],["محطة","İstasyon"],["حمام","Tuvalet"],["واحد","Bir"],["عشرة","On"],["اليوم","Bugün"],["غدا","Yarın"],["الآن","Şimdi"],["مساعدة","Yardım"],["سعر","Fiyat"]], phrases:[["أين الحمام؟","Tuvalet nerede?"],["بكم هذا؟","Bu ne kadar?"],["لا أفهم.","Anlamıyorum."],["قهوة من فضلك.","Kahve lütfen."],["أحتاج مساعدة.","Yardıma ihtiyacım var."],["الحساب من فضلك.","Hesap lütfen."]], lesson:"أين / بكم" },
    s3: { words:[["وقت","Zaman"],["ساعة","Saat"],["أسبوع","Hafta"],["عمل","İş"],["مدرسة","Okul"],["بيت","Ev"],["مدينة","Şehir"],["مشغول","Meşgul"],["لاحقا","Sonra"],["صباح","Sabah"],["مساء","Akşam"],["لقاء","Buluşma"]], phrases:[["كم الساعة؟","Saat kaç?"],["أنا مشغول.","Meşgulüm."],["إلى الغد.","Yarın görüşürüz."],["هل أنت متاح؟","Müsait misin?"],["نلتقي لاحقا.","Sonra buluşalım."],["أنا ذاهب إلى البيت.","Eve gidiyorum."]], lesson:"كم الساعة؟" },
    s4: { words:[["سعيد","Mutlu"],["متعب","Yorgun"],["مهم","Önemli"],["مشكلة","Sorun"],["سفر","Seyahat"],["فندق","Otel"],["تذكرة","Bilet"],["سهل","Kolay"],["صعب","Zor"],["عائلة","Aile"],["حب","Aşk"],["طقس","Hava"]], phrases:[["أنا متعب.","Yorgunum."],["لا مشكلة.","Sorun değil."],["رحلة سعيدة!","İyi yolculuklar!"],["هذا مهم.","Bu önemli."],["كيف الطقس؟","Hava nasıl?"],["أنا أحب هذا.","Bunu seviyorum."]], lesson:"لا مشكلة" },
    s5: { words:[["دائما","Her zaman"],["أبدا","Asla"],["غالبا","Sık"],["أحيانا","Bazen"],["بالفعل","Zaten"],["ما زال","Hâlâ"],["معا","Birlikte"],["بدون","Olmadan"],["لأن","Çünkü"],["لكن","Ama"],["أو","Veya"],["إذن","O zaman"]], phrases:[["أعرف بالفعل.","Zaten biliyorum."],["ليس بعد.","Henüz değil."],["لنذهب معا.","Birlikte gidelim."],["بدون سكر.","Şekersiz."],["لأنني أتعلم.","Çünkü öğreniyorum."],["حسناً.","Tamam."]], lesson:"لأن sebep bağlacı." }
  },
  ko: {
    s1: { words:[["안녕하세요","Merhaba"],["감사합니다","Teşekkürler"],["네","Evet"],["아니요","Hayır"],["이름","İsim"],["친구","Arkadaş"],["물","Su"],["죄송합니다","Özür dilerim"],["주세요","Lütfen"],["좋아요","İyi"],["안녕히 가세요","Hoşça kalın"],["만나서 반가워요","Memnun oldum"]], phrases:[["어떻게 지내세요?","Nasılsınız?"],["잘 지내요.","İyiyim."],["이름이 뭐예요?","Adınız ne?"],["나중에 봐요.","Sonra görüşürüz."],["좋은 하루 보내세요.","İyi günler."],["도움이 필요해요.","Yardıma ihtiyacım var."]], lesson:"요/습니다 saygı düzeyleri." },
    s2: { words:[["화장실","Tuvalet"],["역","İstasyon"],["얼마","Ne kadar"],["어디","Nerede"],["오늘","Bugün"],["내일","Yarın"],["지금","Şimdi"],["음식","Yiyecek"],["돈","Para"],["도움","Yardım"],["커피","Kahve"],["조금","Biraz"]], phrases:[["화장실 어디에 있어요?","Tuvalet nerede?"],["얼마예요?","Ne kadar?"],["모르겠어요.","Bilmiyorum."],["물 주세요.","Su lütfen."],["도와주세요.","Yardım edin."],["영어 하세요?","İngilizce biliyor musunuz?"]], lesson:"어디에 있어요?" },
    s3: { words:[["시간","Zaman"],["시","Saat"],["주","Hafta"],["월요일","Pazartesi"],["바빠요","Meşgulüm"],["나중에","Sonra"],["집","Ev"],["학교","Okul"],["일","İş"],["도시","Şehir"],["만나요","Buluşalım"],["오늘","Bugün"]], phrases:[["지금 몇 시예요?","Saat kaç?"],["오늘 바빠요.","Bugün meşgulüm."],["내일 봐요.","Yarın görüşürüz."],["시간 있어요?","Zamanın var mı?"],["나중에 만나요.","Sonra buluşalım."],["집에 가요.","Eve gidiyorum."]], lesson:"몇 시예요?" },
    s4: { words:[["행복","Mutluluk"],["피곤","Yorgun"],["중요","Önemli"],["문제","Sorun"],["여행","Seyahat"],["호텔","Otel"],["표","Bilet"],["쉬워요","Kolay"],["어려워요","Zor"],["가족","Aile"],["사랑","Aşk"],["날씨","Hava"]], phrases:[["피곤해요.","Yorgunum."],["문제 없어요.","Sorun yok."],["좋은 여행 하세요!","İyi yolculuklar!"],["중요해요.","Önemli."],["날씨 어때요?","Hava nasıl?"],["이거 좋아요.","Bu güzel."]], lesson:"문제 없어요" },
    s5: { words:[["항상","Her zaman"],["절대","Asla"],["자주","Sık"],["가끔","Bazen"],["이미","Zaten"],["아직","Hâlâ"],["같이","Birlikte"],["없이","Olmadan"],["왜냐하면","Çünkü"],["하지만","Ama"],["또는","Veya"],["그래서","Bu yüzden"]], phrases:[["이미 알아요.","Zaten biliyorum."],["아직 안 돼요.","Henüz olmaz."],["같이 가요.","Birlikte gidelim."],["설탕 없이요.","Şekersiz."],["공부하고 있어서요.","Çünkü ders çalışıyorum."],["괜찮아요.","Sorun değil."]], lesson:"이미 / 아직" }
  },
  zh: {
    s1: { words:[["你好","Merhaba"],["谢谢","Teşekkürler"],["请","Lütfen"],["是","Evet"],["不","Hayır"],["名字","İsim"],["朋友","Arkadaş"],["水","Su"],["对不起","Özür dilerim"],["再见","Hoşça kal"],["好","İyi"],["早上","Sabah"]], phrases:[["你好吗？","Nasılsın?"],["我很好。","İyiyim."],["你叫什么名字？","Adın ne?"],["很高兴认识你。","Memnun oldum."],["明天见。","Yarın görüşürüz."],["祝你愉快。","İyi günler."]], lesson:"Tonlar anlam değiştirir." },
    s2: { words:[["厕所","Tuvalet"],["车站","İstasyon"],["多少","Ne kadar"],["哪里","Nerede"],["今天","Bugün"],["明天","Yarın"],["现在","Şimdi"],["食物","Yiyecek"],["钱","Para"],["帮助","Yardım"],["咖啡","Kahve"],["一点","Biraz"]], phrases:[["厕所在哪里？","Tuvalet nerede?"],["多少钱？","Ne kadar?"],["我不懂。","Anlamıyorum."],["请给我水。","Su lütfen."],["帮帮我。","Bana yardım et."],["你会说英语吗？","İngilizce konuşur musun?"]], lesson:"在哪里？" },
    s3: { words:[["时间","Zaman"],["点","Saat"],["星期","Hafta"],["星期一","Pazartesi"],["忙","Meşgul"],["以后","Sonra"],["家","Ev"],["学校","Okul"],["工作","İş"],["城市","Şehir"],["见面","Buluşmak"],["今天","Bugün"]], phrases:[["现在几点？","Saat kaç?"],["我很忙。","Çok meşgulüm."],["明天见。","Yarın görüşürüz."],["你有空吗？","Boş vaktin var mı?"],["以后见。","Sonra görüşürüz."],["我回家。","Eve gidiyorum."]], lesson:"现在几点？" },
    s4: { words:[["高兴","Mutlu"],["累","Yorgun"],["重要","Önemli"],["问题","Sorun"],["旅行","Seyahat"],["酒店","Otel"],["票","Bilet"],["容易","Kolay"],["难","Zor"],["家庭","Aile"],["爱","Aşk"],["天气","Hava"]], phrases:[["我累了。","Yoruldum."],["没问题。","Sorun değil."],["一路顺风！","İyi yolculuklar!"],["这很重要。","Bu önemli."],["天气怎么样？","Hava nasıl?"],["我喜欢这个。","Bunu seviyorum."]], lesson:"没问题" },
    s5: { words:[["总是","Her zaman"],["从不","Asla"],["经常","Sık"],["有时","Bazen"],["已经","Zaten"],["还","Hâlâ"],["一起","Birlikte"],["没有","Yok"],["因为","Çünkü"],["但是","Ama"],["或者","Veya"],["所以","Bu yüzden"]], phrases:[["我已经知道了。","Zaten biliyorum."],["还没有。","Henüz yok."],["我们一起去。","Birlikte gidelim."],["不要糖。","Şekersiz."],["因为我在学习。","Çünkü öğreniyorum."],["好的。","Tamam."]], lesson:"因为…所以…" }
  },
  ru: {
    s1: { words:[["Привет","Merhaba"],["Спасибо","Teşekkürler"],["Пожалуйста","Lütfen"],["Да","Evet"],["Нет","Hayır"],["Имя","İsim"],["Друг","Arkadaş"],["Вода","Su"],["Извините","Özür dilerim"],["Пока","Hoşça kal"],["Хорошо","İyi"],["Доброе утро","Günaydın"]], phrases:[["Как дела?","Nasılsın?"],["Хорошо.","İyiyim."],["Как вас зовут?","Adınız ne?"],["Приятно познакомиться.","Memnun oldum."],["До свидания.","Görüşürüz."],["Хорошего дня.","İyi günler."]], lesson:"вы resmi, ты samimi." },
    s2: { words:[["Еда","Yemek"],["Кофе","Kahve"],["Улица","Sokak"],["Станция","İstasyon"],["Туалет","Tuvalet"],["Один","Bir"],["Десять","On"],["Сегодня","Bugün"],["Завтра","Yarın"],["Сейчас","Şimdi"],["Помощь","Yardım"],["Цена","Fiyat"]], phrases:[["Где туалет?","Tuvalet nerede?"],["Сколько это стоит?","Ne kadar?"],["Я не понимаю.","Anlamıyorum."],["Кофе, пожалуйста.","Kahve lütfen."],["Мне нужна помощь.","Yardıma ihtiyacım var."],["Счёт, пожалуйста.","Hesap lütfen."]], lesson:"Где / Сколько" },
    s3: { words:[["Время","Zaman"],["Час","Saat"],["Неделя","Hafta"],["Понедельник","Pazartesi"],["Занят","Meşgul"],["Потом","Sonra"],["Дом","Ev"],["Школа","Okul"],["Работа","İş"],["Город","Şehir"],["Встреча","Buluşma"],["Утро","Sabah"]], phrases:[["Который час?","Saat kaç?"],["Я занят.","Meşgulüm."],["До завтра.","Yarın görüşürüz."],["Ты свободен?","Boş musun?"],["Увидимся позже.","Sonra görüşürüz."],["Я иду домой.","Eve gidiyorum."]], lesson:"Который час?" },
    s4: { words:[["Счастливый","Mutlu"],["Усталый","Yorgun"],["Важный","Önemli"],["Проблема","Sorun"],["Путешествие","Seyahat"],["Отель","Otel"],["Билет","Bilet"],["Лёгкий","Kolay"],["Трудный","Zor"],["Семья","Aile"],["Любовь","Aşk"],["Погода","Hava"]], phrases:[["Я устал.","Yoruldum."],["Нет проблем.","Sorun yok."],["Счастливого пути!","İyi yolculuklar!"],["Это важно.","Bu önemli."],["Какая погода?","Hava nasıl?"],["Мне это нравится.","Bunu beğeniyorum."]], lesson:"Нет проблем" },
    s5: { words:[["Всегда","Her zaman"],["Никогда","Asla"],["Часто","Sık"],["Иногда","Bazen"],["Уже","Zaten"],["Ещё","Hâlâ"],["Вместе","Birlikte"],["Без","Olmadan"],["Потому что","Çünkü"],["Но","Ama"],["Или","Veya"],["Поэтому","Bu yüzden"]], phrases:[["Я уже знаю.","Zaten biliyorum."],["Ещё нет.","Henüz değil."],["Пойдём вместе.","Birlikte gidelim."],["Без сахара.","Şekersiz."],["Потому что я учусь.","Çünkü öğreniyorum."],["Хорошо.","Tamam."]], lesson:"уже / ещё нет" }
  },
  tr: {
    s1: { words:[["Merhaba","Hello"],["Teşekkürler","Thank you"],["Lütfen","Please"],["Evet","Yes"],["Hayır","No"],["Ad","Name"],["Arkadaş","Friend"],["Su","Water"],["Özür dilerim","Sorry"],["Hoşça kal","Goodbye"],["İyi","Good"],["Günaydın","Good morning"]], phrases:[["Nasılsın?","How are you?"],["İyiyim.","I'm fine."],["Adın ne?","What's your name?"],["Memnun oldum.","Nice to meet you."],["Sonra görüşürüz.","See you later."],["İyi günler.","Have a nice day."]], lesson:"Yabancılar için Türkçe temeller." },
    s2: { words:[["Yemek","Food"],["Kahve","Coffee"],["Sokak","Street"],["İstasyon","Station"],["Tuvalet","Bathroom"],["Bir","One"],["On","Ten"],["Bugün","Today"],["Yarın","Tomorrow"],["Şimdi","Now"],["Yardım","Help"],["Fiyat","Price"]], phrases:[["Tuvalet nerede?","Where is the bathroom?"],["Ne kadar?","How much?"],["Anlamıyorum.","I don't understand."],["Bir kahve lütfen.","A coffee please."],["Yardıma ihtiyacım var.","I need help."],["Hesap lütfen.","The bill please."]], lesson:"mi/mı/mu/mü soru eki." },
    s3: { words:[["Zaman","Time"],["Saat","Hour"],["Hafta","Week"],["Pazartesi","Monday"],["Meşgul","Busy"],["Sonra","Later"],["Ev","Home"],["Okul","School"],["İş","Work"],["Şehir","City"],["Buluşmak","To meet"],["Sabah","Morning"]], phrases:[["Saat kaç?","What time is it?"],["Meşgulüm.","I'm busy."],["Yarın görüşürüz.","See you tomorrow."],["Boş musun?","Are you free?"],["Sonra buluşalım.","Let's meet later."],["Eve gidiyorum.","I'm going home."]], lesson:"Saat kaç?" },
    s4: { words:[["Mutlu","Happy"],["Yorgun","Tired"],["Önemli","Important"],["Sorun","Problem"],["Seyahat","Travel"],["Otel","Hotel"],["Bilet","Ticket"],["Kolay","Easy"],["Zor","Difficult"],["Aile","Family"],["Aşk","Love"],["Hava","Weather"]], phrases:[["Yorgunum.","I'm tired."],["Sorun değil.","No problem."],["İyi yolculuklar!","Have a good trip!"],["Bu önemli.","It's important."],["Hava nasıl?","How's the weather?"],["Bunu seviyorum.","I like this."]], lesson:"Yorgunum, mutluyum..." },
    s5: { words:[["Her zaman","Always"],["Asla","Never"],["Sık sık","Often"],["Bazen","Sometimes"],["Çoktan","Already"],["Hâlâ","Still"],["Birlikte","Together"],["Olmadan","Without"],["Çünkü","Because"],["Ama","But"],["Veya","Or"],["Bu yüzden","Therefore"]], phrases:[["Zaten biliyorum.","I already know."],["Henüz değil.","Not yet."],["Birlikte gidelim.","Let's go together."],["Şekersiz.","Without sugar."],["Çünkü öğreniyorum.","Because I'm learning."],["Tamam.","Okay."]], lesson:"çünkü, ama, bu yüzden" }
  }
};

// Gerçek 5 etaplı paketler (diğer diller)
const REAL = {
  it: {
    s1: { words:[["Ciao","Merhaba"],["Buongiorno","Günaydın"],["Grazie","Teşekkürler"],["Per favore","Lütfen"],["Sì","Evet"],["No","Hayır"],["Scusa","Özür dilerim"],["Amico","Arkadaş"],["Nome","İsim"],["Bene","İyi"],["Acqua","Su"],["Arrivederci","Hoşça kal"]], phrases:[["Come stai?","Nasılsın?"],["Sto bene.","İyiyim."],["Come ti chiami?","Adın ne?"],["Piacere.","Memnun oldum."],["A dopo.","Sonra görüşürüz."],["Buona giornata.","İyi günler."]], lesson:"Ciao samimi; Buongiorno daha resmi." },
    s2: { words:[["Cibo","Yemek"],["Caffè","Kahve"],["Soldi","Para"],["Strada","Sokak"],["Stazione","İstasyon"],["Bagno","Tuvalet"],["Uno","Bir"],["Dieci","On"],["Oggi","Bugün"],["Domani","Yarın"],["Aiuto","Yardım"],["Prezzo","Fiyat"]], phrases:[["Dov'è il bagno?","Tuvalet nerede?"],["Quanto costa?","Ne kadar?"],["Non capisco.","Anlamıyorum."],["Un caffè, per favore.","Bir kahve lütfen."],["Mi serve aiuto.","Yardıma ihtiyacım var."],["Il conto, per favore.","Hesap lütfen."]], lesson:"Quanto costa? alışverişte." },
    s3: { words:[["Tempo","Zaman"],["Ora","Saat"],["Settimana","Hafta"],["Lunedì","Pazartesi"],["Libero","Boş"],["Occupato","Meşgul"],["Adesso","Şimdi"],["Dopo","Sonra"],["Lavoro","İş"],["Scuola","Okul"],["Casa","Ev"],["Città","Şehir"]], phrases:[["Che ora è?","Saat kaç?"],["Sono occupato.","Meşgulüm."],["A domani.","Yarın görüşürüz."],["Sei libero?","Boş musun?"],["Ci vediamo dopo.","Sonra görüşürüz."],["Vado a casa.","Eve gidiyorum."]], lesson:"Che ora è?" },
    s4: { words:[["Felice","Mutlu"],["Stanco","Yorgun"],["Importante","Önemli"],["Problema","Sorun"],["Viaggio","Seyahat"],["Hotel","Otel"],["Biglietto","Bilet"],["Facile","Kolay"],["Difficile","Zor"],["Famiglia","Aile"],["Amore","Aşk"],["Tempo","Hava"]], phrases:[["Sono stanco.","Yorgunum."],["Nessun problema.","Sorun değil."],["Buon viaggio!","İyi yolculuklar!"],["È importante.","Önemli."],["Che tempo fa?","Hava nasıl?"],["Mi piace questo.","Bunu beğeniyorum."]], lesson:"Mi piace = beğeniyorum." },
    s5: { words:[["Sempre","Her zaman"],["Mai","Asla"],["Spesso","Sık"],["A volte","Bazen"],["Già","Zaten"],["Ancora","Hâlâ"],["Insieme","Birlikte"],["Senza","Olmadan"],["Perché","Çünkü"],["Ma","Ama"],["O","Veya"],["Quindi","Bu yüzden"]], phrases:[["Lo so già.","Zaten biliyorum."],["Non ancora.","Henüz değil."],["Andiamo insieme.","Birlikte gidelim."],["Senza zucchero.","Şekersiz."],["Perché sto imparando.","Çünkü öğreniyorum."],["Va bene.","Tamam."]], lesson:"Già / non ancora." }
  },
  pt: {
    s1: { words:[["Olá","Merhaba"],["Bom dia","Günaydın"],["Obrigado","Teşekkürler"],["Por favor","Lütfen"],["Sim","Evet"],["Não","Hayır"],["Desculpe","Özür dilerim"],["Amigo","Arkadaş"],["Nome","İsim"],["Bem","İyi"],["Água","Su"],["Tchau","Hoşça kal"]], phrases:[["Como vai?","Nasılsın?"],["Estou bem.","İyiyim."],["Qual é o seu nome?","Adın ne?"],["Prazer.","Memnun oldum."],["Até logo.","Sonra görüşürüz."],["Tenha um bom dia.","İyi günler."]], lesson:"Obrigado (e) / Obrigada (k)." },
    s2: { words:[["Comida","Yemek"],["Café","Kahve"],["Dinheiro","Para"],["Rua","Sokak"],["Estação","İstasyon"],["Banheiro","Tuvalet"],["Um","Bir"],["Dez","On"],["Hoje","Bugün"],["Amanhã","Yarın"],["Ajuda","Yardım"],["Preço","Fiyat"]], phrases:[["Onde fica o banheiro?","Tuvalet nerede?"],["Quanto custa?","Ne kadar?"],["Não entendo.","Anlamıyorum."],["Um café, por favor.","Bir kahve lütfen."],["Preciso de ajuda.","Yardıma ihtiyacım var."],["A conta, por favor.","Hesap lütfen."]], lesson:"Quanto custa?" },
    s3: { words:[["Tempo","Zaman"],["Hora","Saat"],["Semana","Hafta"],["Segunda","Pazartesi"],["Livre","Boş"],["Ocupado","Meşgul"],["Agora","Şimdi"],["Depois","Sonra"],["Trabalho","İş"],["Escola","Okul"],["Casa","Ev"],["Cidade","Şehir"]], phrases:[["Que horas são?","Saat kaç?"],["Estou ocupado.","Meşgulüm."],["Até amanhã.","Yarın görüşürüz."],["Você está livre?","Boş musun?"],["Nos vemos depois.","Sonra görüşürüz."],["Vou para casa.","Eve gidiyorum."]], lesson:"Que horas são?" },
    s4: { words:[["Feliz","Mutlu"],["Cansado","Yorgun"],["Importante","Önemli"],["Problema","Sorun"],["Viagem","Seyahat"],["Hotel","Otel"],["Bilhete","Bilet"],["Fácil","Kolay"],["Difícil","Zor"],["Família","Aile"],["Amor","Aşk"],["Clima","Hava"]], phrases:[["Estou cansado.","Yorgunum."],["Sem problema.","Sorun değil."],["Boa viagem!","İyi yolculuklar!"],["É importante.","Önemli."],["Como está o clima?","Hava nasıl?"],["Eu gosto disso.","Bunu beğeniyorum."]], lesson:"Sem problema." },
    s5: { words:[["Sempre","Her zaman"],["Nunca","Asla"],["Muitas vezes","Sık"],["Às vezes","Bazen"],["Já","Zaten"],["Ainda","Hâlâ"],["Juntos","Birlikte"],["Sem","Olmadan"],["Porque","Çünkü"],["Mas","Ama"],["Ou","Veya"],["Então","O zaman"]], phrases:[["Eu já sei.","Zaten biliyorum."],["Ainda não.","Henüz değil."],["Vamos juntos.","Birlikte gidelim."],["Sem açúcar.","Şekersiz."],["Porque estou aprendendo.","Çünkü öğreniyorum."],["Tudo bem.","Tamam."]], lesson:"Já / ainda não." }
  },
  nl: {
    s1: { words:[["Hallo","Merhaba"],["Goedemorgen","Günaydın"],["Dank je","Teşekkürler"],["Alsjeblieft","Lütfen"],["Ja","Evet"],["Nee","Hayır"],["Sorry","Özür dilerim"],["Vriend","Arkadaş"],["Naam","İsim"],["Goed","İyi"],["Water","Su"],["Tot ziens","Hoşça kal"]], phrases:[["Hoe gaat het?","Nasılsın?"],["Het gaat goed.","İyiyim."],["Hoe heet je?","Adın ne?"],["Aangenaam.","Memnun oldum."],["Tot later.","Sonra görüşürüz."],["Fijne dag.","İyi günler."]], lesson:"Dank je / Dank u (resmi)." },
    s2: { words:[["Eten","Yemek"],["Koffie","Kahve"],["Geld","Para"],["Straat","Sokak"],["Station","İstasyon"],["Toilet","Tuvalet"],["Een","Bir"],["Tien","On"],["Vandaag","Bugün"],["Morgen","Yarın"],["Hulp","Yardım"],["Prijs","Fiyat"]], phrases:[["Waar is het toilet?","Tuvalet nerede?"],["Hoeveel kost het?","Ne kadar?"],["Ik begrijp het niet.","Anlamıyorum."],["Een koffie, alsjeblieft.","Bir kahve lütfen."],["Ik heb hulp nodig.","Yardıma ihtiyacım var."],["De rekening, alstublieft.","Hesap lütfen."]], lesson:"Hoeveel kost het?" },
    s3: { words:[["Tijd","Zaman"],["Uur","Saat"],["Week","Hafta"],["Maandag","Pazartesi"],["Vrij","Boş"],["Druk","Meşgul"],["Nu","Şimdi"],["Later","Sonra"],["Werk","İş"],["School","Okul"],["Huis","Ev"],["Stad","Şehir"]], phrases:[["Hoe laat is het?","Saat kaç?"],["Ik ben druk.","Meşgulüm."],["Tot morgen.","Yarın görüşürüz."],["Ben je vrij?","Boş musun?"],["Tot later.","Sonra görüşürüz."],["Ik ga naar huis.","Eve gidiyorum."]], lesson:"Hoe laat is het?" },
    s4: { words:[["Gelukkig","Mutlu"],["Moe","Yorgun"],["Belangrijk","Önemli"],["Probleem","Sorun"],["Reis","Seyahat"],["Hotel","Otel"],["Ticket","Bilet"],["Makkelijk","Kolay"],["Moeilijk","Zor"],["Familie","Aile"],["Liefde","Aşk"],["Weer","Hava"]], phrases:[["Ik ben moe.","Yorgunum."],["Geen probleem.","Sorun değil."],["Goede reis!","İyi yolculuklar!"],["Het is belangrijk.","Önemli."],["Hoe is het weer?","Hava nasıl?"],["Ik vind dit leuk.","Bunu beğeniyorum."]], lesson:"Geen probleem." },
    s5: { words:[["Altijd","Her zaman"],["Nooit","Asla"],["Vaak","Sık"],["Soms","Bazen"],["Al","Zaten"],["Nog","Hâlâ"],["Samen","Birlikte"],["Zonder","Olmadan"],["Omdat","Çünkü"],["Maar","Ama"],["Of","Veya"],["Dus","Bu yüzden"]], phrases:[["Ik weet het al.","Zaten biliyorum."],["Nog niet.","Henüz değil."],["Laten we samen gaan.","Birlikte gidelim."],["Zonder suiker.","Şekersiz."],["Omdat ik leer.","Çünkü öğreniyorum."],["Oké.","Tamam."]], lesson:"Al / nog niet." }
  },
  pl: {
    s1: { words:[["Cześć","Merhaba"],["Dzień dobry","Günaydın"],["Dziękuję","Teşekkürler"],["Proszę","Lütfen"],["Tak","Evet"],["Nie","Hayır"],["Przepraszam","Özür dilerim"],["Przyjaciel","Arkadaş"],["Imię","İsim"],["Dobrze","İyi"],["Woda","Su"],["Do widzenia","Hoşça kal"]], phrases:[["Jak się masz?","Nasılsın?"],["Dobrze.","İyiyim."],["Jak masz na imię?","Adın ne?"],["Miło mi.","Memnun oldum."],["Do zobaczenia.","Görüşürüz."],["Miłego dnia.","İyi günler."]], lesson:"Cześć samimi; Dzień dobry resmi." },
    s2: { words:[["Jedzenie","Yemek"],["Kawa","Kahve"],["Pieniądze","Para"],["Ulica","Sokak"],["Stacja","İstasyon"],["Toaleta","Tuvalet"],["Jeden","Bir"],["Dziesięć","On"],["Dziś","Bugün"],["Jutro","Yarın"],["Pomoc","Yardım"],["Cena","Fiyat"]], phrases:[["Gdzie jest toaleta?","Tuvalet nerede?"],["Ile to kosztuje?","Ne kadar?"],["Nie rozumiem.","Anlamıyorum."],["Kawę, proszę.","Kahve lütfen."],["Potrzebuję pomocy.","Yardıma ihtiyacım var."],["Rachunek, proszę.","Hesap lütfen."]], lesson:"Ile to kosztuje?" },
    s3: { words:[["Czas","Zaman"],["Godzina","Saat"],["Tydzień","Hafta"],["Poniedziałek","Pazartesi"],["Wolny","Boş"],["Zajęty","Meşgul"],["Teraz","Şimdi"],["Później","Sonra"],["Praca","İş"],["Szkoła","Okul"],["Dom","Ev"],["Miasto","Şehir"]], phrases:[["Która godzina?","Saat kaç?"],["Jestem zajęty.","Meşgulüm."],["Do jutra.","Yarın görüşürüz."],["Jesteś wolny?","Boş musun?"],["Do zobaczenia później.","Sonra görüşürüz."],["Idę do domu.","Eve gidiyorum."]], lesson:"Która godzina?" },
    s4: { words:[["Szczęśliwy","Mutlu"],["Zmęczony","Yorgun"],["Ważny","Önemli"],["Problem","Sorun"],["Podróż","Seyahat"],["Hotel","Otel"],["Bilet","Bilet"],["Łatwy","Kolay"],["Trudny","Zor"],["Rodzina","Aile"],["Miłość","Aşk"],["Pogoda","Hava"]], phrases:[["Jestem zmęczony.","Yorgunum."],["Nie ma problemu.","Sorun değil."],["Miłej podróży!","İyi yolculuklar!"],["To ważne.","Önemli."],["Jaka jest pogoda?","Hava nasıl?"],["Lubię to.","Bunu beğeniyorum."]], lesson:"Nie ma problemu." },
    s5: { words:[["Zawsze","Her zaman"],["Nigdy","Asla"],["Często","Sık"],["Czasami","Bazen"],["Już","Zaten"],["Jeszcze","Hâlâ"],["Razem","Birlikte"],["Bez","Olmadan"],["Bo","Çünkü"],["Ale","Ama"],["Albo","Veya"],["Więc","Bu yüzden"]], phrases:[["Już wiem.","Zaten biliyorum."],["Jeszcze nie.","Henüz değil."],["Chodźmy razem.","Birlikte gidelim."],["Bez cukru.","Şekersiz."],["Bo się uczę.","Çünkü öğreniyorum."],["Dobrze.","Tamam."]], lesson:"Już / jeszcze nie." }
  },
  hi: {
    s1: { words:[["नमस्ते","Merhaba"],["धन्यवाद","Teşekkürler"],["कृपया","Lütfen"],["हाँ","Evet"],["नहीं","Hayır"],["माफ़ कीजिए","Özür dilerim"],["दोस्त","Arkadaş"],["नाम","İsim"],["पानी","Su"],["अच्छा","İyi"],["अलविदा","Hoşça kal"],["सुप्रभात","Günaydın"]], phrases:[["कैसे हो?","Nasılsın?"],["मैं ठीक हूँ।","İyiyim."],["आपका नाम क्या है?","Adınız ne?"],["मिलकर खुशी हुई।","Memnun oldum."],["फिर मिलेंगे।","Sonra görüşürüz."],["आपका दिन शुभ हो।","İyi günler."]], lesson:"नमस्ते genel selam." },
    s2: { words:[["खाना","Yemek"],["कॉफ़ी","Kahve"],["पैसे","Para"],["सड़क","Sokak"],["स्टेशन","İstasyon"],["शौचालय","Tuvalet"],["एक","Bir"],["दस","On"],["आज","Bugün"],["कल","Yarın"],["मदद","Yardım"],["कीमत","Fiyat"]], phrases:[["शौचालय कहाँ है?","Tuvalet nerede?"],["यह कितने का है?","Bu ne kadar?"],["मुझे समझ नहीं आया।","Anlamadım."],["एक कॉफ़ी दीजिए।","Bir kahve lütfen."],["मुझे मदद चाहिए।","Yardıma ihtiyacım var."],["बिल दीजिए।","Hesap lütfen."]], lesson:"कहाँ = nerede." },
    s3: { words:[["समय","Zaman"],["घंटा","Saat"],["हफ़्ता","Hafta"],["सोमवार","Pazartesi"],["व्यस्त","Meşgul"],["बाद में","Sonra"],["घर","Ev"],["स्कूल","Okul"],["काम","İş"],["शहर","Şehir"],["सुबह","Sabah"],["शाम","Akşam"]], phrases:[["क्या समय हुआ है?","Saat kaç?"],["मैं व्यस्त हूँ।","Meşgulüm."],["कल मिलते हैं।","Yarın görüşürüz."],["क्या आप फ़ारिग हैं?","Boş musunuz?"],["बाद में मिलते हैं।","Sonra buluşalım."],["मैं घर जा रहा हूँ।","Eve gidiyorum."]], lesson:"समय sorma kalıbı." },
    s4: { words:[["खुश","Mutlu"],["थका","Yorgun"],["ज़रूरी","Önemli"],["समस्या","Sorun"],["यात्रा","Seyahat"],["होटल","Otel"],["टिकट","Bilet"],["आसान","Kolay"],["मुश्किल","Zor"],["परिवार","Aile"],["प्यार","Aşk"],["मौसम","Hava"]], phrases:[["मैं थक गया हूँ।","Yoruldum."],["कोई बात नहीं।","Sorun değil."],["शुभ यात्रा!","İyi yolculuklar!"],["यह ज़रूरी है।","Bu önemli."],["मौसम कैसा है?","Hava nasıl?"],["मुझे यह पसंद है।","Bunu beğeniyorum."]], lesson:"कोई बात नहीं." },
    s5: { words:[["हमेशा","Her zaman"],["कभी नहीं","Asla"],["अक्सर","Sık"],["कभी-कभी","Bazen"],["पहले से","Zaten"],["अभी भी","Hâlâ"],["साथ","Birlikte"],["बिना","Olmadan"],["क्योंकि","Çünkü"],["लेकिन","Ama"],["या","Veya"],["इसलिए","Bu yüzden"]], phrases:[["मुझे पहले से पता है।","Zaten biliyorum."],["अभी नहीं।","Henüz değil."],["चलो साथ चलें।","Birlikte gidelim."],["बिना चीनी के।","Şekersiz."],["क्योंकि मैं सीख रहा हूँ।","Çünkü öğreniyorum."],["ठीक है।","Tamam."]], lesson:"क्योंकि sebep." }
  },
  id: {
    s1: { words:[["Halo","Merhaba"],["Selamat pagi","Günaydın"],["Terima kasih","Teşekkürler"],["Tolong","Lütfen"],["Ya","Evet"],["Tidak","Hayır"],["Maaf","Özür dilerim"],["Teman","Arkadaş"],["Nama","İsim"],["Baik","İyi"],["Air","Su"],["Selamat tinggal","Hoşça kal"]], phrases:[["Apa kabar?","Nasılsın?"],["Baik-baik saja.","İyiyim."],["Siapa nama Anda?","Adınız ne?"],["Senang bertemu.","Memnun oldum."],["Sampai jumpa.","Görüşürüz."],["Semoga harimu menyenangkan.","İyi günler."]], lesson:"Bahasa Indonesia şeffaf yazılır." },
    s2: { words:[["Makanan","Yemek"],["Kopi","Kahve"],["Uang","Para"],["Jalan","Sokak"],["Stasiun","İstasyon"],["Toilet","Tuvalet"],["Satu","Bir"],["Sepuluh","On"],["Hari ini","Bugün"],["Besok","Yarın"],["Bantuan","Yardım"],["Harga","Fiyat"]], phrases:[["Di mana toilet?","Tuvalet nerede?"],["Berapa harganya?","Ne kadar?"],["Saya tidak mengerti.","Anlamıyorum."],["Satu kopi, tolong.","Bir kahve lütfen."],["Saya butuh bantuan.","Yardıma ihtiyacım var."],["Minta bonnya.","Hesap lütfen."]], lesson:"Di mana / Berapa" },
    s3: { words:[["Waktu","Zaman"],["Jam","Saat"],["Minggu","Hafta"],["Senin","Pazartesi"],["Sibuk","Meşgul"],["Nanti","Sonra"],["Rumah","Ev"],["Sekolah","Okul"],["Kerja","İş"],["Kota","Şehir"],["Pagi","Sabah"],["Malam","Akşam"]], phrases:[["Jam berapa sekarang?","Saat kaç?"],["Saya sibuk.","Meşgulüm."],["Sampai besok.","Yarın görüşürüz."],["Apa kamu bebas?","Boş musun?"],["Ketemu nanti.","Sonra buluşalım."],["Saya pulang.","Eve dönüyorum."]], lesson:"Jam berapa?" },
    s4: { words:[["Bahagia","Mutlu"],["Lelah","Yorgun"],["Penting","Önemli"],["Masalah","Sorun"],["Perjalanan","Seyahat"],["Hotel","Otel"],["Tiket","Bilet"],["Mudah","Kolay"],["Sulit","Zor"],["Keluarga","Aile"],["Cinta","Aşk"],["Cuaca","Hava"]], phrases:[["Saya lelah.","Yorgunum."],["Tidak masalah.","Sorun değil."],["Selamat jalan!","İyi yolculuklar!"],["Ini penting.","Bu önemli."],["Bagaimana cuacanya?","Hava nasıl?"],["Saya suka ini.","Bunu beğeniyorum."]], lesson:"Tidak masalah." },
    s5: { words:[["Selalu","Her zaman"],["Tidak pernah","Asla"],["Sering","Sık"],["Kadang","Bazen"],["Sudah","Zaten"],["Masih","Hâlâ"],["Bersama","Birlikte"],["Tanpa","Olmadan"],["Karena","Çünkü"],["Tapi","Ama"],["Atau","Veya"],["Jadi","Bu yüzden"]], phrases:[["Saya sudah tahu.","Zaten biliyorum."],["Belum.","Henüz değil."],["Ayo pergi bersama.","Birlikte gidelim."],["Tanpa gula.","Şekersiz."],["Karena saya belajar.","Çünkü öğreniyorum."],["Oke.","Tamam."]], lesson:"Sudah / belum." }
  },
  vi: {
    s1: { words:[["Xin chào","Merhaba"],["Cảm ơn","Teşekkürler"],["Làm ơn","Lütfen"],["Có","Evet"],["Không","Hayır"],["Xin lỗi","Özür dilerim"],["Bạn","Arkadaş"],["Tên","İsim"],["Nước","Su"],["Tốt","İyi"],["Tạm biệt","Hoşça kal"],["Chào buổi sáng","Günaydın"]], phrases:[["Bạn khỏe không?","Nasılsın?"],["Tôi khỏe.","İyiyim."],["Bạn tên gì?","Adın ne?"],["Rất vui được gặp bạn.","Memnun oldum."],["Hẹn gặp lại.","Görüşürüz."],["Chúc một ngày tốt lành.","İyi günler."]], lesson:"Tonlar anlamı değiştirir." },
    s2: { words:[["Thức ăn","Yemek"],["Cà phê","Kahve"],["Tiền","Para"],["Đường","Sokak"],["Nhà ga","İstasyon"],["Nhà vệ sinh","Tuvalet"],["Một","Bir"],["Mười","On"],["Hôm nay","Bugün"],["Ngày mai","Yarın"],["Giúp đỡ","Yardım"],["Giá","Fiyat"]], phrases:[["Nhà vệ sinh ở đâu?","Tuvalet nerede?"],["Bao nhiêu tiền?","Ne kadar?"],["Tôi không hiểu.","Anlamıyorum."],["Một cà phê, làm ơn.","Bir kahve lütfen."],["Tôi cần giúp đỡ.","Yardıma ihtiyacım var."],["Tính tiền, làm ơn.","Hesap lütfen."]], lesson:"Ở đâu = nerede." },
    s3: { words:[["Thời gian","Zaman"],["Giờ","Saat"],["Tuần","Hafta"],["Thứ hai","Pazartesi"],["Bận","Meşgul"],["Sau","Sonra"],["Nhà","Ev"],["Trường","Okul"],["Việc","İş"],["Thành phố","Şehir"],["Sáng","Sabah"],["Tối","Akşam"]], phrases:[["Bây giờ mấy giờ?","Saat kaç?"],["Tôi bận.","Meşgulüm."],["Hẹn gặp lại ngày mai.","Yarın görüşürüz."],["Bạn có rảnh không?","Boş musun?"],["Gặp lại sau.","Sonra görüşürüz."],["Tôi về nhà.","Eve dönüyorum."]], lesson:"Mấy giờ?" },
    s4: { words:[["Vui","Mutlu"],["Mệt","Yorgun"],["Quan trọng","Önemli"],["Vấn đề","Sorun"],["Du lịch","Seyahat"],["Khách sạn","Otel"],["Vé","Bilet"],["Dễ","Kolay"],["Khó","Zor"],["Gia đình","Aile"],["Yêu","Aşk"],["Thời tiết","Hava"]], phrases:[["Tôi mệt.","Yorgunum."],["Không sao.","Sorun değil."],["Chúc đi đường an toàn!","İyi yolculuklar!"],["Điều này quan trọng.","Bu önemli."],["Thời tiết thế nào?","Hava nasıl?"],["Tôi thích cái này.","Bunu beğeniyorum."]], lesson:"Không sao." },
    s5: { words:[["Luôn luôn","Her zaman"],["Không bao giờ","Asla"],["Thường","Sık"],["Thỉnh thoảng","Bazen"],["Đã","Zaten"],["Vẫn","Hâlâ"],["Cùng nhau","Birlikte"],["Không có","Olmadan"],["Vì","Çünkü"],["Nhưng","Ama"],["Hoặc","Veya"],["Vì vậy","Bu yüzden"]], phrases:[["Tôi đã biết.","Zaten biliyorum."],["Chưa.","Henüz değil."],["Đi cùng nhau đi.","Birlikte gidelim."],["Không đường.","Şekersiz."],["Vì tôi đang học.","Çünkü öğreniyorum."],["Được.","Tamam."]], lesson:"Đã / chưa." }
  },
  th: {
    s1: { words:[["สวัสดี","Merhaba"],["ขอบคุณ","Teşekkürler"],["กรุณา","Lütfen"],["ใช่","Evet"],["ไม่","Hayır"],["ขอโทษ","Özür dilerim"],["เพื่อน","Arkadaş"],["ชื่อ","İsim"],["น้ำ","Su"],["ดี","İyi"],["ลาก่อน","Hoşça kal"],["สวัสดีตอนเช้า","Günaydın"]], phrases:[["สบายดีไหม","Nasılsın?"],["สบายดี","İyiyim."],["คุณชื่ออะไร","Adın ne?"],["ยินดีที่ได้รู้จัก","Memnun oldum."],["แล้วพบกันใหม่","Sonra görüşürüz."],["ขอให้เป็นวันที่ดี","İyi günler."]], lesson:"สวัสดี / สวัสดีครับ/ค่ะ" },
    s2: { words:[["อาหาร","Yemek"],["กาแฟ","Kahve"],["เงิน","Para"],["ถนน","Sokak"],["สถานี","İstasyon"],["ห้องน้ำ","Tuvalet"],["หนึ่ง","Bir"],["สิบ","On"],["วันนี้","Bugün"],["พรุ่งนี้","Yarın"],["ช่วย","Yardım"],["ราคา","Fiyat"]], phrases:[["ห้องน้ำอยู่ที่ไหน","Tuvalet nerede?"],["เท่าไหร่","Ne kadar?"],["ฉันไม่เข้าใจ","Anlamıyorum."],["กาแฟหนึ่งแก้ว","Bir kahve."],["ฉันต้องการความช่วยเหลือ","Yardıma ihtiyacım var."],["เช็คบิลด้วย","Hesap lütfen."]], lesson:"ที่ไหน = nerede." },
    s3: { words:[["เวลา","Zaman"],["ชั่วโมง","Saat"],["สัปดาห์","Hafta"],["วันจันทร์","Pazartesi"],["ยุ่ง","Meşgul"],["ทีหลัง","Sonra"],["บ้าน","Ev"],["โรงเรียน","Okul"],["งาน","İş"],["เมือง","Şehir"],["เช้า","Sabah"],["เย็น","Akşam"]], phrases:[["กี่โมงแล้ว","Saat kaç?"],["ฉันยุ่ง","Meşgulüm."],["พรุ้งนี้พบกัน","Yarın görüşürüz."],["ว่างไหม","Boş musun?"],["ไว้พบกันทีหลัง","Sonra buluşalım."],["ฉันกำลังกลับบ้าน","Eve dönüyorum."]], lesson:"กี่โมง" },
    s4: { words:[["มีความสุข","Mutlu"],["เหนื่อย","Yorgun"],["สำคัญ","Önemli"],["ปัญหา","Sorun"],["การเดินทาง","Seyahat"],["โรงแรม","Otel"],["ตั๋ว","Bilet"],["ง่าย","Kolay"],["ยาก","Zor"],["ครอบครัว","Aile"],["รัก","Aşk"],["อากาศ","Hava"]], phrases:[["ฉันเหนื่อย","Yorgunum."],["ไม่เป็นไร","Sorun değil."],["เดินทางปลอดภัย","İyi yolculuklar!"],["สิ่งนี้สำคัญ","Bu önemli."],["อากาศเป็นอย่างไร","Hava nasıl?"],["ฉันชอบอันนี้","Bunu beğeniyorum."]], lesson:"ไม่เป็นไร" },
    s5: { words:[["เสมอ","Her zaman"],["ไม่เคย","Asla"],["บ่อย","Sık"],["บางครั้ง","Bazen"],["แล้ว","Zaten"],["ยัง","Hâlâ"],["ด้วยกัน","Birlikte"],["โดยไม่มี","Olmadan"],["เพราะ","Çünkü"],["แต่","Ama"],["หรือ","Veya"],["ดังนั้น","Bu yüzden"]], phrases:[["ฉันรู้แล้ว","Zaten biliyorum."],["ยังไม่","Henüz değil."],["ไปด้วยกันเถอะ","Birlikte gidelim."],["ไม่ใส่น้ำตาล","Şekersiz."],["เพราะฉันกำลังเรียน","Çünkü öğreniyorum."],["ตกลง","Tamam."]], lesson:"แล้ว / ยัง" }
  },
  sv: {
    s1: { words:[["Hej","Merhaba"],["God morgon","Günaydın"],["Tack","Teşekkürler"],["Snälla","Lütfen"],["Ja","Evet"],["Nej","Hayır"],["Förlåt","Özür dilerim"],["Vän","Arkadaş"],["Namn","İsim"],["Bra","İyi"],["Vatten","Su"],["Hej då","Hoşça kal"]], phrases:[["Hur mår du?","Nasılsın?"],["Jag mår bra.","İyiyim."],["Vad heter du?","Adın ne?"],["Trevligt att träffas.","Memnun oldum."],["Vi ses senare.","Sonra görüşürüz."],["Ha en bra dag.","İyi günler."]], lesson:"Hej her yerde kullanılır." },
    s2: { words:[["Mat","Yemek"],["Kaffe","Kahve"],["Pengar","Para"],["Gata","Sokak"],["Station","İstasyon"],["Toalett","Tuvalet"],["En","Bir"],["Tio","On"],["Idag","Bugün"],["Imorgon","Yarın"],["Hjälp","Yardım"],["Pris","Fiyat"]], phrases:[["Var är toaletten?","Tuvalet nerede?"],["Hur mycket kostar det?","Ne kadar?"],["Jag förstår inte.","Anlamıyorum."],["En kaffe, tack.","Bir kahve lütfen."],["Jag behöver hjälp.","Yardıma ihtiyacım var."],["Notan, tack.","Hesap lütfen."]], lesson:"Hur mycket kostar det?" },
    s3: { words:[["Tid","Zaman"],["Timme","Saat"],["Vecka","Hafta"],["Måndag","Pazartesi"],["Ledig","Boş"],["Upptagen","Meşgul"],["Nu","Şimdi"],["Senare","Sonra"],["Arbete","İş"],["Skola","Okul"],["Hem","Ev"],["Stad","Şehir"]], phrases:[["Vad är klockan?","Saat kaç?"],["Jag är upptagen.","Meşgulüm."],["Vi ses imorgon.","Yarın görüşürüz."],["Är du ledig?","Boş musun?"],["Vi ses senare.","Sonra görüşürüz."],["Jag går hem.","Eve gidiyorum."]], lesson:"Vad är klockan?" },
    s4: { words:[["Glad","Mutlu"],["Trött","Yorgun"],["Viktig","Önemli"],["Problem","Sorun"],["Resa","Seyahat"],["Hotell","Otel"],["Biljett","Bilet"],["Lätt","Kolay"],["Svår","Zor"],["Familj","Aile"],["Kärlek","Aşk"],["Väder","Hava"]], phrases:[["Jag är trött.","Yorgunum."],["Inga problem.","Sorun değil."],["Trevlig resa!","İyi yolculuklar!"],["Det är viktigt.","Önemli."],["Hur är vädret?","Hava nasıl?"],["Jag gillar det här.","Bunu beğeniyorum."]], lesson:"Inga problem." },
    s5: { words:[["Alltid","Her zaman"],["Aldrig","Asla"],["Ofta","Sık"],["Ibland","Bazen"],["Redan","Zaten"],["Fortfarande","Hâlâ"],["Tillsammans","Birlikte"],["Utan","Olmadan"],["För att","Çünkü"],["Men","Ama"],["Eller","Veya"],["Så","Bu yüzden"]], phrases:[["Jag vet redan.","Zaten biliyorum."],["Inte än.","Henüz değil."],["Vi går tillsammans.","Birlikte gidelim."],["Utan socker.","Şekersiz."],["För att jag lär mig.","Çünkü öğreniyorum."],["Okej.","Tamam."]], lesson:"Redan / inte än." }
  },
  he: {
    s1: { words:[["שלום","Merhaba"],["תודה","Teşekkürler"],["בבקשה","Lütfen"],["כן","Evet"],["לא","Hayır"],["סליחה","Özür dilerim"],["חבר","Arkadaş"],["שם","İsim"],["מים","Su"],["טוב","İyi"],["להתראות","Hoşça kal"],["בוקר טוב","Günaydın"]], phrases:[["מה שלומך?","Nasılsın?"],["אני בסדר.","İyiyim."],["מה שמך?","Adın ne?"],["נעים מאוד.","Memnun oldum."],["נתראה אחר כך.","Sonra görüşürüz."],["יום נעים.","İyi günler."]], lesson:"Sağdan sola." },
    s2: { words:[["אוכל","Yemek"],["קפה","Kahve"],["כסף","Para"],["רחוב","Sokak"],["תחנה","İstasyon"],["שירותים","Tuvalet"],["אחד","Bir"],["עשר","On"],["היום","Bugün"],["מחר","Yarın"],["עזרה","Yardım"],["מחיר","Fiyat"]], phrases:[["איפה השירותים?","Tuvalet nerede?"],["כמה זה עולה?","Ne kadar?"],["אני לא מבין.","Anlamıyorum."],["קפה בבקשה.","Kahve lütfen."],["אני צריך עזרה.","Yardıma ihtiyacım var."],["את החשבון בבקשה.","Hesap lütfen."]], lesson:"איפה / כמה" },
    s3: { words:[["זמן","Zaman"],["שעה","Saat"],["שבוע","Hafta"],["יום שני","Pazartesi"],["עסוק","Meşgul"],["אחר כך","Sonra"],["בית","Ev"],["בית ספר","Okul"],["עבודה","İş"],["עיר","Şehir"],["בוקר","Sabah"],["ערב","Akşam"]], phrases:[["מה השעה?","Saat kaç?"],["אני עסוק.","Meşgulüm."],["נתראה מחר.","Yarın görüşürüz."],["אתה פנוי?","Boş musun?"],["נתראה אחר כך.","Sonra görüşürüz."],["אני הולך הביתה.","Eve gidiyorum."]], lesson:"מה השעה?" },
    s4: { words:[["שמח","Mutlu"],["עייף","Yorgun"],["חשוב","Önemli"],["בעיה","Sorun"],["נסיעה","Seyahat"],["מלון","Otel"],["כרטיס","Bilet"],["קל","Kolay"],["קשה","Zor"],["משפחה","Aile"],["אהבה","Aşk"],["מזג אוויר","Hava"]], phrases:[["אני עייף.","Yorgunum."],["אין בעיה.","Sorun değil."],["נסיעה טובה!","İyi yolculuklar!"],["זה חשוב.","Bu önemli."],["איך מזג האוויר?","Hava nasıl?"],["אני אוהב את זה.","Bunu seviyorum."]], lesson:"אין בעיה" },
    s5: { words:[["תמיד","Her zaman"],["לעולם לא","Asla"],["לעיתים קרובות","Sık"],["לפעמים","Bazen"],["כבר","Zaten"],["עדיין","Hâlâ"],["ביחד","Birlikte"],["בלי","Olmadan"],["כי","Çünkü"],["אבל","Ama"],["או","Veya"],["לכן","Bu yüzden"]], phrases:[["אני כבר יודע.","Zaten biliyorum."],["עדיין לא.","Henüz değil."],["בואו נלך ביחד.","Birlikte gidelim."],["בלי סוכר.","Şekersiz."],["כי אני לומד.","Çünkü öğreniyorum."],["בסדר.","Tamam."]], lesson:"כבר / עדיין לא" }
  },
  fa: {
    s1: { words:[["سلام","Merhaba"],["متشکرم","Teşekkürler"],["لطفاً","Lütfen"],["بله","Evet"],["نه","Hayır"],["ببخشید","Özür dilerim"],["دوست","Arkadaş"],["اسم","İsim"],["آب","Su"],["خوب","İyi"],["خداحافظ","Hoşça kal"],["صبح بخیر","Günaydın"]], phrases:[["حالت چطوره؟","Nasılsın?"],["خوبم.","İyiyim."],["اسمت چیه؟","Adın ne?"],["از آشنایی خوشبختم.","Memnun oldum."],["بعداً می‌بینمت.","Sonra görüşürüz."],["روز خوبی داشته باشی.","İyi günler."]], lesson:"سلام genel selam." },
    s2: { words:[["غذا","Yemek"],["قهوه","Kahve"],["پول","Para"],["خیابان","Sokak"],["ایستگاه","İstasyon"],["دستشویی","Tuvalet"],["یک","Bir"],["ده","On"],["امروز","Bugün"],["فردا","Yarın"],["کمک","Yardım"],["قیمت","Fiyat"]], phrases:[["دستشویی کجاست؟","Tuvalet nerede?"],["چقدر است؟","Ne kadar?"],["نمی‌فهمم.","Anlamıyorum."],["یک قهوه لطفاً.","Bir kahve lütfen."],["به کمک نیاز دارم.","Yardıma ihtiyacım var."],["حساب لطفاً.","Hesap lütfen."]], lesson:"کجا / چقدر" },
    s3: { words:[["وقت","Zaman"],["ساعت","Saat"],["هفته","Hafta"],["دوشنبه","Pazartesi"],["مشغول","Meşgul"],["بعداً","Sonra"],["خانه","Ev"],["مدرسه","Okul"],["کار","İş"],["شهر","Şehir"],["صبح","Sabah"],["شب","Akşam"]], phrases:[["ساعت چنده؟","Saat kaç?"],["مشغولم.","Meşgulüm."],["فردا می‌بینمت.","Yarın görüşürüz."],["آزادی؟","Boş musun?"],["بعداً می‌بینیم.","Sonra görüşürüz."],["دارم می‌رم خونه.","Eve gidiyorum."]], lesson:"ساعت چنده؟" },
    s4: { words:[["خوشحال","Mutlu"],["خسته","Yorgun"],["مهم","Önemli"],["مشکل","Sorun"],["سفر","Seyahat"],["هتل","Otel"],["بلیط","Bilet"],["آسان","Kolay"],["سخت","Zor"],["خانواده","Aile"],["عشق","Aşk"],["هوا","Hava"]], phrases:[["خسته‌ام.","Yorgunum."],["مشکلی نیست.","Sorun değil."],["سفر خوبی!","İyi yolculuklar!"],["این مهم است.","Bu önemli."],["هوا چطوره؟","Hava nasıl?"],["این را دوست دارم.","Bunu beğeniyorum."]], lesson:"مشکلی نیست" },
    s5: { words:[["همیشه","Her zaman"],["هرگز","Asla"],["اغلب","Sık"],["گاهی","Bazen"],["قبلاً","Zaten"],["هنوز","Hâlâ"],["با هم","Birlikte"],["بدون","Olmadan"],["چون","Çünkü"],["اما","Ama"],["یا","Veya"],["پس","Bu yüzden"]], phrases:[["از قبل می‌دانم.","Zaten biliyorum."],["هنوز نه.","Henüz değil."],["با هم برویم.","Birlikte gidelim."],["بدون شکر.","Şekersiz."],["چون دارم یاد می‌گیرم.","Çünkü öğreniyorum."],["باشه.","Tamam."]], lesson:"چون sebep." }
  },
  sw: {
    s1: { words:[["Habari","Merhaba"],["Asante","Teşekkürler"],["Tafadhali","Lütfen"],["Ndiyo","Evet"],["Hapana","Hayır"],["Samahani","Özür dilerim"],["Rafiki","Arkadaş"],["Jina","İsim"],["Maji","Su"],["Nzuri","İyi"],["Kwaheri","Hoşça kal"],["Habari za asubuhi","Günaydın"]], phrases:[["Habari yako?","Nasılsın?"],["Nzuri.","İyiyim."],["Jina lako nani?","Adın ne?"],["Nimefurahi kukutana nawe.","Memnun oldum."],["Tutaonana baadaye.","Sonra görüşürüz."],["Siku njema.","İyi günler."]], lesson:"Habari genel selam." },
    s2: { words:[["Chakula","Yemek"],["Kahawa","Kahve"],["Pesa","Para"],["Barabara","Sokak"],["Kituo","İstasyon"],["Choo","Tuvalet"],["Moja","Bir"],["Kumi","On"],["Leo","Bugün"],["Kesho","Yarın"],["Msaada","Yardım"],["Bei","Fiyat"]], phrases:[["Choo kiko wapi?","Tuvalet nerede?"],["Bei gani?","Ne kadar?"],["Sielevi.","Anlamıyorum."],["Kahawa moja, tafadhali.","Bir kahve lütfen."],["Nahitaji msaada.","Yardıma ihtiyacım var."],["Bill, tafadhali.","Hesap lütfen."]], lesson:"Wapi / Bei gani" },
    s3: { words:[["Wakati","Zaman"],["Saa","Saat"],["Wiki","Hafta"],["Jumatatu","Pazartesi"],["Busy","Meşgul"],["Baadaye","Sonra"],["Nyumbani","Ev"],["Shule","Okul"],["Kazi","İş"],["Jiji","Şehir"],["Asubuhi","Sabah"],["Jioni","Akşam"]], phrases:[["Saa ngapi?","Saat kaç?"],["Nina shughuli.","Meşgulüm."],["Tutaonana kesho.","Yarın görüşürüz."],["Uko huru?","Boş musun?"],["Tutaonana baadaye.","Sonra görüşürüz."],["Naenda nyumbani.","Eve gidiyorum."]], lesson:"Saa ngapi?" },
    s4: { words:[["Furaha","Mutluluk"],["Uchovu","Yorgunluk"],["Muhimu","Önemli"],["Shida","Sorun"],["Safari","Seyahat"],["Hoteli","Otel"],["Tiketi","Bilet"],["Rahisi","Kolay"],["Ngumu","Zor"],["Familia","Aile"],["Upendo","Aşk"],["Hali ya hewa","Hava"]], phrases:[["Nimechoka.","Yoruldum."],["Hakuna shida.","Sorun değil."],["Safari njema!","İyi yolculuklar!"],["Hii ni muhimu.","Bu önemli."],["Hali ya hewa iko vipi?","Hava nasıl?"],["Napenda hii.","Bunu seviyorum."]], lesson:"Hakuna shida." },
    s5: { words:[["Kila wakati","Her zaman"],["Kamwe","Asla"],["Mara nyingi","Sık"],["Mara kwa mara","Bazen"],["Tayari","Zaten"],["Bado","Hâlâ"],["Pamoja","Birlikte"],["Bila","Olmadan"],["Kwa sababu","Çünkü"],["Lakini","Ama"],["Au","Veya"],["Kwa hiyo","Bu yüzden"]], phrases:[["Najua tayari.","Zaten biliyorum."],["Bado hapana.","Henüz değil."],["Twende pamoja.","Birlikte gidelim."],["Bila sukari.","Şekersiz."],["Kwa sababu najifunza.","Çünkü öğreniyorum."],["Sawa.","Tamam."]], lesson:"Tayari / bado" }
  }
};

// Eksik diller için REAL'ten türet veya genel gerçek kalıp
const EXTRA_MAP = {
  no: "sv", da: "sv", fi: "sv", el: "it", cs: "pl", ro: "it", hu: "pl", uk: "ru",
  bg: "ru", hr: "pl", sr: "ru", sk: "cs", lt: "pl", lv: "pl", et: "fi", ga: "en",
  ca: "es", ku: "tr", az: "tr", bn: "hi", ur: "hi", ms: "id", tl: "id",
  my: "th", km: "th", lo: "th", mn: "zh", ne: "hi", si: "hi",
  am: "ar", yo: "sw", zu: "sw", ha: "sw", la: "it"
};

function clonePack(src) {
  return JSON.parse(JSON.stringify(src));
}

function getLangContent(langId) {
  if (PACKS[langId]) return PACKS[langId];
  if (REAL[langId]) return REAL[langId];
  const map = EXTRA_MAP[langId];
  if (map && (PACKS[map] || REAL[map])) {
    const base = clonePack(PACKS[map] || REAL[map]);
    Object.keys(base).forEach(k => {
      base[k].lesson = (base[k].lesson || "") + " Bu dil için gerçek kalıplar yakındır; yapı aynı etap sistemidir.";
    });
    return base;
  }
  return clonePack(PACKS.en);
}
