// 55 dil — bölge + temel bilgi
const LANG_META = [
  { id:"en", name:"İngilizce", flag:"🇬🇧", region:"europe", speakers:"1.4B+" },
  { id:"de", name:"Almanca", flag:"🇩🇪", region:"europe", speakers:"130M+" },
  { id:"fr", name:"Fransızca", flag:"🇫🇷", region:"europe", speakers:"280M+" },
  { id:"es", name:"İspanyolca", flag:"🇪🇸", region:"europe", speakers:"500M+" },
  { id:"it", name:"İtalyanca", flag:"🇮🇹", region:"europe", speakers:"85M+" },
  { id:"pt", name:"Portekizce", flag:"🇵🇹", region:"europe", speakers:"260M+" },
  { id:"nl", name:"Hollandaca", flag:"🇳🇱", region:"europe", speakers:"25M+" },
  { id:"pl", name:"Lehçe", flag:"🇵🇱", region:"europe", speakers:"45M+" },
  { id:"sv", name:"İsveççe", flag:"🇸🇪", region:"europe", speakers:"10M+" },
  { id:"no", name:"Norveççe", flag:"🇳🇴", region:"europe", speakers:"5M+" },
  { id:"da", name:"Danca", flag:"🇩🇰", region:"europe", speakers:"6M+" },
  { id:"fi", name:"Fince", flag:"🇫🇮", region:"europe", speakers:"5M+" },
  { id:"el", name:"Yunanca", flag:"🇬🇷", region:"europe", speakers:"13M+" },
  { id:"cs", name:"Çekçe", flag:"🇨🇿", region:"europe", speakers:"10M+" },
  { id:"ro", name:"Romence", flag:"🇷🇴", region:"europe", speakers:"24M+" },
  { id:"hu", name:"Macarca", flag:"🇭🇺", region:"europe", speakers:"13M+" },
  { id:"uk", name:"Ukraynaca", flag:"🇺🇦", region:"europe", speakers:"40M+" },
  { id:"ru", name:"Rusça", flag:"🇷🇺", region:"europe", speakers:"250M+" },
  { id:"bg", name:"Bulgarca", flag:"🇧🇬", region:"europe", speakers:"8M+" },
  { id:"hr", name:"Hırvatça", flag:"🇭🇷", region:"europe", speakers:"5M+" },
  { id:"sr", name:"Sırpça", flag:"🇷🇸", region:"europe", speakers:"9M+" },
  { id:"sk", name:"Slovakça", flag:"🇸🇰", region:"europe", speakers:"5M+" },
  { id:"lt", name:"Litvanca", flag:"🇱🇹", region:"europe", speakers:"3M+" },
  { id:"lv", name:"Letonca", flag:"🇱🇻", region:"europe", speakers:"2M+" },
  { id:"et", name:"Estonca", flag:"🇪🇪", region:"europe", speakers:"1M+" },
  { id:"ga", name:"İrlandaca", flag:"🇮🇪", region:"europe", speakers:"2M+" },
  { id:"ca", name:"Katalanca", flag:"🇦🇩", region:"europe", speakers:"10M+" },
  { id:"tr", name:"Türkçe", flag:"🇹🇷", region:"mideast", speakers:"90M+" },
  { id:"ar", name:"Arapça", flag:"🇸🇦", region:"mideast", speakers:"400M+" },
  { id:"fa", name:"Farsça", flag:"🇮🇷", region:"mideast", speakers:"110M+" },
  { id:"he", name:"İbranice", flag:"🇮🇱", region:"mideast", speakers:"9M+" },
  { id:"ku", name:"Kürtçe", flag:"🇹🇯", region:"mideast", speakers:"30M+" },
  { id:"az", name:"Azerbaycan Türkçesi", flag:"🇦🇿", region:"mideast", speakers:"25M+" },
  { id:"ja", name:"Japonca", flag:"🇯🇵", region:"asia", speakers:"125M+" },
  { id:"ko", name:"Korece", flag:"🇰🇷", region:"asia", speakers:"80M+" },
  { id:"zh", name:"Çince (Mandarin)", flag:"🇨🇳", region:"asia", speakers:"1B+" },
  { id:"hi", name:"Hintçe", flag:"🇮🇳", region:"asia", speakers:"600M+" },
  { id:"bn", name:"Bengalce", flag:"🇧🇩", region:"asia", speakers:"270M+" },
  { id:"ur", name:"Urduca", flag:"🇵🇰", region:"asia", speakers:"230M+" },
  { id:"id", name:"Endonezce", flag:"🇮🇩", region:"asia", speakers:"200M+" },
  { id:"ms", name:"Malayca", flag:"🇲🇾", region:"asia", speakers:"30M+" },
  { id:"vi", name:"Vietnamca", flag:"🇻🇳", region:"asia", speakers:"85M+" },
  { id:"th", name:"Tayca", flag:"🇹🇭", region:"asia", speakers:"60M+" },
  { id:"tl", name:"Filipince", flag:"🇵🇭", region:"asia", speakers:"45M+" },
  { id:"my", name:"Birmanca", flag:"🇲🇲", region:"asia", speakers:"33M+" },
  { id:"km", name:"Kmerce", flag:"🇰🇭", region:"asia", speakers:"16M+" },
  { id:"lo", name:"Laoca", flag:"🇱🇦", region:"asia", speakers:"7M+" },
  { id:"mn", name:"Moğolca", flag:"🇲🇳", region:"asia", speakers:"5M+" },
  { id:"ne", name:"Nepalce", flag:"🇳🇵", region:"asia", speakers:"16M+" },
  { id:"si", name:"Seylanca", flag:"🇱🇰", region:"asia", speakers:"16M+" },
  { id:"sw", name:"Svahili", flag:"🇰🇪", region:"other", speakers:"100M+" },
  { id:"am", name:"Amharca", flag:"🇪🇹", region:"other", speakers:"30M+" },
  { id:"yo", name:"Yoruba", flag:"🇳🇬", region:"other", speakers:"40M+" },
  { id:"zu", name:"Zulu", flag:"🇿🇦", region:"other", speakers:"12M+" },
  { id:"ha", name:"Hausa", flag:"🇳🇬", region:"other", speakers:"70M+" },
  { id:"la", name:"Latince", flag:"🏛️", region:"other", speakers:"Klasik" }
];

const STAGE_NAMES = [
  { id: "s1", title: "1. Etap — Temeller", desc: "Selamlaşma, nazik ifadeler, en sık kelimeler" },
  { id: "s2", title: "2. Etap — Günlük hayat", desc: "Yemek, yön sorma, alışveriş, sayılar" },
  { id: "s3", title: "3. Etap — Konuşma pratiği", desc: "Diyaloglar, zaman, plan yapma" },
  { id: "s4", title: "4. Etap — Orta seviye", desc: "Duygular, iş, seyahat, daha uzun cümleler" },
  { id: "s5", title: "5. Etap — Sınav yolu", desc: "Genel tekrar ve etap sonu sınavı" }
];
